name: Decider

parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_PDS_all_tissues_labels.csv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/PDS/features_UNI/pt_files"
  cnv_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/CopyNumbers/PDS_PurifiedLogR.tsv"
  genomics_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/Gene_expression/Expression/PDS_bulk_counts.tsv"
  embedding_size_SLIDE_LEVEL: [768]
  tissue_type_filter: ["Ome", "Ova", "Per", "Tub", "Oth", "Adn", "Mes", "Ute", "Vag", "LNR", "Bow", "And"]
  task_type: "Survival"
  label_name: "FUT"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"