name: Decider_chemorefractory 

parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_chemorefractory_all_tissues_labels.csv"
  genomics_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/Gene_expression/Expression/Chemorefractory_bulk_counts.tsv"
  cnv_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/CopyNumbers/Chemorefractory_PurifiedLogR.tsv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/chemorefractory/features_UNI/pt_files"
  pt_files_path_SLIDE_LEVEL: ['/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/chemorefractory/slide_embeddings_TITAN']
  embedding_size_SLIDE_LEVEL: [768]
  tissue_type_filter: ["Ome", "Ova", "Per", "Tub", "Oth", "Adn", "Mes", "Ute", "Vag", "LNR", "Bow", "And"]
  task_type: "Treatment_Response"
  label_name: "Treatment_Response"
  censorships_name: "None"
  case_id_name: "case_id"
  slide_id_name: "slide_id"
  missing_modalities_table_path : /work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/utils/missing_mod/chemorefractory_missing_modality_table.csv