name: NACT_interval_PFI

parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_NACT_interval_PFI_cohort_all_tissues_labels.csv"
  genomics_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/Gene_expression/Expression/NACT_interval_bulk_counts.tsv"
  cnv_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/CopyNumbers/NACT_interval_PurifiedLogR.tsv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/NACT/interval/features_UNI/pt_files"
  tissue_type_filter: ["Ome", "Ova", "Per", "Tub", "Oth", "Adn", "Mes", "Ute", "Vag", "LNR", "Bow", "And"]
  task_type: "Treatment_Response"
  label_name: "Treatment_Response"
  censorships_name: "None"
  case_id_name: "case_id"
  slide_id_name: "slide_id"