name: NACT_interval_PFI_regression 

parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_chemorefractory_all_tissues_labels.csv"
  genomics_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/Gene_expression/Expression/Chemorefractory_bulk_counts.tsv"
  cnv_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/CopyNumbers/Chemorefractory_PurifiedLogR.tsv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/chemorefractory/features_UNI/pt_files"
  tissue_type_filter: ["Ome", "Ova", "Per", "Tub", "Oth", "Adn", "Mes", "Ute", "Vag", "LNR", "Bow", "And"]
  task_type: "Survival"
  label_name: "PFI"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"