name: Decider
parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_NACT_interval_labels.csv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/NACT/interval/features_UNI/pt_files"
  tissue_type_filter: ["Ome"]
  task_type: "Survival"
  label_name: "FUT"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"