name: Decider_chemorefractory

parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/Decider_chemorefractory_all_tissues_labels.csv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/DECIDER_cohorts/chemorefractory/features_UNI/pt_files"
  tissue_type_filter: ["Ome", "Ova"]
  task_type: "Treatment_Response"
  label_name: "Treatment_Response"
  censorships_name: "None"
  case_id_name: "case_id"
  slide_id_name: "slide_id"