name: TCGA_BRCA
parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/TCGA_BRCA_labels.csv"
  pt_files_path: "/work/h2020deciderficarra_shared/TCGA/BRCA/features_UNI/pt_files"
  tissue_type_filter: [""]
  label_name: "FUT"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"