name: TCGA_LUAD
parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/TCGA_LUAD_labels.csv"
  genomics_path: "/work/h2020deciderficarra_shared/TCGA/LUAD/gene_expression/fpkm_unstranded.csv"
  pt_files_path: "/work/h2020deciderficarra_shared/TCGA/LUAD/features_UNI/pt_files"
  tissue_type_filter: [""]
  task_type: "Survival"
  label_name: "FUT"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"
  missing_modalities_table_path: /work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/utils/missing_mod/LUAD_missing_modality_table.csv