name: TCGA_BRCA
parameters:
  dataframe_path: "LAB_WSI_Genomics/TCGA_BRCA/TCGA_BRCA_labels_multimodal.tsv"
  pt_files_path: "LAB_WSI_Genomics/TCGA_BRCA/Data/wsi/features_UNI/pt_files"
  tissue_type_filter: [""]
  label_name: "FUT"
  censorships_name: "Survival"
  case_id_name: "case_id"
  slide_id_name: "slide_id"