name: OBR_expandedv2
parameters:
  dataframe_path: "/work/H2020DeciderFicarra/D2_4/Development/MultimodalDecider/dataloader/dataset/OBR_expandedv2_all_tissues_labels.csv"
  pt_files_path: "/work/H2020DeciderFicarra/D2_4/datasets/OBR/features_UNI/pt_files"
  pt_files_path_SLIDE_LEVEL: ['/work/H2020DeciderFicarra/D2_4/datasets/OBR/slide_embeddings_TITAN']
  embedding_size_SLIDE_LEVEL: [768]
  tissue_type_filter: ["Ova"]
  task_type: "Treatment_Response"
  label_name: "Treatment_Response"
  censorships_name: "None"
  case_id_name: "case_id"
  slide_id_name: "slide_id"