title: OXA_MISS_kfold_5_demo_test
project_dir: 'demo_test/results'
seed: 42

wandb:
  mode: online

data_loader:

  missing_modalities_tables: 
    active: True 
    missing_mod_rate: complete
  missing_modality_table : demo_test/KIRC_missing_modality_table.csv
  
  file_genes_group: "genes_groups/pathways_ensg.json"
  datasets_configs: ["demo_test/TCGA_KIRC_dataset_demo_test.yaml"]
  task_type: "Survival"
  max_patches: 4096
  batch_size: 1
  real_batch_size: 4
  n_bins: 4
  sample: True
  test_sample: False
  load_slides_in_RAM: True  
  label_name: "Survival"
  censorships_name: "None"
  eps: 0.000001
  num_workers: 2
  train_size: 0.7
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  preprocessing: config/preprocessing.yaml
  augmentation: config/augmentation.yaml
  KFold:
    splits: demo_test/splits/KIRC
    internal_val_size: 0.0

missing_modality_test:
  active: True
  test_scenarios_on_each_epoch: True
  scenarios: [
    'complete',
    'wsi_miss_100',
    'genomics_miss_100',
  ]  
model:
  name: OXA_MISS
  pretrained: False 
  save_checkpoints: True
  kwargs:
    input_dim: 1024
    genomics_group_name: [ "tumor_suppression", "oncogenesis","protein_kinases", "cellular_differentiation","cytokines_and_growth"] 
    genomics_group_dropout: [0.35] 
    cnv_group_name: [ "tumor_suppression", "oncogenesis","protein_kinases", "cellular_differentiation","cytokines_and_growth"] 
    cnv_group_dropout: [0.2]
    inner_dim: 256
    num_latent_queries: 2
    wsi_dropout: 0.0
    use_layernorm: False
    dropout: 0.5 
    output_dim: 4
    input_modalities: ["WSI", "Genomics"]

    use_WSI_level_embs: False
    WSI_level_embs_fusion_type: "concat" 
    WSI_level_encoder_dropout: 0.2
    WSI_level_encoder_sizes: [768, 40, 3]
    WSI_level_encoder_LayerNorm: False 
  device: cuda

# loss:
#   name: CrossEntropyLoss
#   kwargs:
#     label_smoothing: 0.0
#     reduction: 'mean'
#     weight: [2, 1]

# Survival Loss
loss:
  name: NLLSurvLoss
  kwargs:
    alpha: 0.0
    eps: 0.0000001
    reduction: 'mean'

scheduler:
  batch_step: False
  name: MultiStepLR
  milestones: [10]
  gamma: 0.2
  pct_start: 0.1
  steps_per_epoch: 1

optimizer:
  learning_rate: 0.001
  name: RAdam
  weight_decay: 0.0001 # 0 # 0.00005
  momentum: None

trainer:
  reload: False
  checkpoint: 'demo_test/chekpoints_KIRC'
  do_train: False
  do_test: True
  do_inference: False
  do_kfold: False
  epochs: 20
  patience: 20
  AEM_lamda: 0.3
  Save_XA_attention_files: True
  grid_search_versions_path: grid_search/models_versions